### ISSUE TITLE
pro values

### ISSUE THREAD

**Issue by ikwattro** [GraphStory/graph-kit-php#1]
Hello,

I discovered Graphkit yesterday on Twitter. I'm already involved a lot with PHP and Neo4j with the [neoxygen](https://github.com/neoxygen) components.

Can you explain me a bit what is the pro's of using graphkit, compared to graphenedb for e.g. , I didn't found the trailer and infos on the GraphStory website really in depth.

Thank you and happy to know new guys loving php and neo4j

Chris

**Comment by jeremykendall** [comment]
Hey @ikwattro,

Thanks for stopping by and thanks for the questions.

> I'm already involved a lot with PHP and Neo4j with the neoxygen components.

Awesome.

> Can you explain me a bit what is the pro's of using graphkit, compared to graphenedb ...

Where Graph Story provides a graph-as-a-service platform, the Graph Kit for PHP is a tool that will help developers learn how to create PHP applications that make use of graph databases. The Graph Kit allows devs to see a graph-based application in action **and** allows them to dig into the code to see how it all works.  

What's especially cool about the Graph Kit is the data that we provide on our platform (because what would a graph app be without its data?). Once you have an account (the [developer account](http://graphstory.com/pricing.php) is free :+1:), you can import the Graph Kit data into your graph database with a single click. Voila, instant graph learning!

> I didn't found the trailer and infos on the GraphStory website really in depth.

Totally understand. We're actually working on documentation right now. In the meantime, you can check out our first Graph Kit blog post, ["Announcing the Graph Kit for PHP"](https://www.graphstory.com/site/wp/2014/10/13/announcing-the-graph-kit-for-php/). It's the first in a series - we'll publish part 2 on Monday.

> Thank you ...

You're welcome! 

> ... and happy to know new guys loving php and neo4j

Likewise!

**Comment by ikwattro** [comment]
Thanks for your reply. I created an account and will definitely give it a try. Keep up the graph ;-)

Chris

**Comment by jeremykendall** [comment]
That's awesome! Please feel free to ping me directly if you have any questions, concerns, problems, or suggestions.

> Keep up the graph

Indeed. We shall :-)

Jeremy
